import 'package:hive_flutter/hive_flutter.dart';
import '../models/movie.dart';

/// Offline storage service using Hive
class OfflineService {
  static const String _moviesBoxName = 'movies';
  static const String _settingsBoxName = 'settings';

  static Box<Movie>? _moviesBox;
  static Box<dynamic>? _settingsBox;

  /// Initialize Hive and open boxes
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(MovieAdapter());
    }

    // Open boxes
    _moviesBox = await Hive.openBox<Movie>(_moviesBoxName);
    _settingsBox = await Hive.openBox(_settingsBoxName);
  }

  /// Get movies box
  static Box<Movie> get moviesBox {
    if (_moviesBox == null || !_moviesBox!.isOpen) {
      throw Exception('Movies box not initialized');
    }
    return _moviesBox!;
  }

  /// Get settings box
  static Box<dynamic> get settingsBox {
    if (_settingsBox == null || !_settingsBox!.isOpen) {
      throw Exception('Settings box not initialized');
    }
    return _settingsBox!;
  }

  // ============ MOVIES CACHE ============

  /// Cache movies for offline viewing
  Future<void> cacheMovies(List<Movie> movies) async {
    for (final movie in movies) {
      await moviesBox.put(movie.id, movie);
    }
  }

  /// Cache single movie
  Future<void> cacheMovie(Movie movie) async {
    await moviesBox.put(movie.id, movie);
  }

  /// Get all cached movies
  List<Movie> getCachedMovies() {
    return moviesBox.values.toList();
  }

  /// Get cached movie by ID
  Movie? getCachedMovie(String id) {
    return moviesBox.get(id);
  }

  /// Remove movie from cache
  Future<void> removeCachedMovie(String id) async {
    await moviesBox.delete(id);
  }

  /// Clear all cached movies
  Future<void> clearMoviesCache() async {
    await moviesBox.clear();
  }

  /// Get cache size in bytes (approximate)
  int getCacheSize() {
    final movies = getCachedMovies();
    // Rough estimate: 500 bytes per movie metadata
    return movies.length * 500;
  }

  // ============ SETTINGS ============

  /// Save setting
  Future<void> saveSetting(String key, dynamic value) async {
    await settingsBox.put(key, value);
  }

  /// Get setting
  T? getSetting<T>(String key, {T? defaultValue}) {
    return settingsBox.get(key, defaultValue: defaultValue) as T?;
  }

  /// Remove setting
  Future<void> removeSetting(String key) async {
    await settingsBox.delete(key);
  }

  // ============ THEME SETTINGS ============

  /// Save theme mode (true = dark, false = light)
  Future<void> saveThemeMode(bool isDark) async {
    await saveSetting('theme_mode', isDark);
  }

  /// Get theme mode
  bool getThemeMode() {
    return getSetting<bool>('theme_mode', defaultValue: true) ?? true;
  }

  // ============ PLAYBACK SETTINGS ============

  /// Save preferred video quality
  Future<void> saveVideoQuality(String quality) async {
    await saveSetting('video_quality', quality);
  }

  /// Get preferred video quality
  String getVideoQuality() {
    return getSetting<String>('video_quality', defaultValue: 'auto') ?? 'auto';
  }

  /// Save autoplay setting
  Future<void> saveAutoplay(bool autoplay) async {
    await saveSetting('autoplay', autoplay);
  }

  /// Get autoplay setting
  bool getAutoplay() {
    return getSetting<bool>('autoplay', defaultValue: true) ?? true;
  }

  // ============ CACHE MANAGEMENT ============

  /// Get formatted cache size
  String getFormattedCacheSize() {
    final bytes = getCacheSize();
    if (bytes < 1024) return '$bytes B';
    if (bytes < 1024 * 1024) return '${(bytes / 1024).toStringAsFixed(1)} KB';
    return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
  }

  /// Clear all app data
  Future<void> clearAllData() async {
    await moviesBox.clear();
    await settingsBox.clear();
  }

  /// Close all boxes
  Future<void> close() async {
    await _moviesBox?.close();
    await _settingsBox?.close();
  }
}
